config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => "registrations"
  }

  root 'home#index'
  resources :users, :only => [:show, :edit, :update]
  resources :menus, :only => [:index, :show]

  namespace :admin do
    root 'admin#index'
    resources :menus
    resources :users
  end

end

app/models/menu.rb
class Menu < ActiveRecord::Base
	before_save :multiply_price
	has_many :orders
	mount_uploader :image, ImageUploader

	def multiply_price
		self.price = self.price * 1000
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :menu
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
	before_action :authenticate_admin
	layout 'admin'

	def index
		
	end

	def is_admin(user)
		!user.admin.zero? ? true : false
	end

	private
	def authenticate_admin
		unless current_user
			if is_admin(current_user)
				redirect_to admin_root_path
			else
				render :file => 'public/403.html', :status => :forbidden, :layout => false
			end
		end
	end
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < Admin::AdminController

	def index
		@column_names = Menu.column_names - ['id', 'created_at', 'updated_at']
		@menus = Menu.all.order(:day)
	end

	def new
		@menu = Menu.new
	end

	def create
		@menu = Menu.new(menu_params)
		if @menu.save
			flash[:success] = "Menu successfully created."
			redirect_to admin_menus_path
		else
			flash[:error] = "Menu failed to be created."
			render "new"
		end
	end

	def show
		@menu = Menu.find(params[:id])
	end

	def edit
		@menu = Menu.find(params[:id])
	end

	def update
		@menu = Menu.find(params[:id])
		if @menu.update_attributes(menu_params)
			flash[:success] = "Update success."
			redirect_to admin_menus_path
		else
			flash[:error] = "Update failed."
			render "edit"
		end
	end

	def destroy
		@menu = Menu.find(params[:id])
		flash[:success] = false
		if @menu.destroy
			flash[:success] = true
		end
		redirect_to admin_menus_path
	end

	private

	def menu_params
		params.require(:menu).permit(:name, :price, :image, :day, :discount, :rating)
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

	def index
		@users = User.all
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_params, if: :devise_controller?
  before_action :user_logon

  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :password, :password_confirmation, :first_name, :last_name, :phone_number, :address, :gender, :birthday)
    end
  end

  def user_logon
  	if current_user
			@user = current_user
		else
			@user = User.new
		end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		
	end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

	def index
		@menus = Menu.where(:day => Time.now.wday)
		@items = @menus.each_slice(3).to_a
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def create
		build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
	end

	def after_sign_up_path_for(resource)
		new_user_session_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])	
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(user_params)
		redirect_to user_path(@user)
	end

	private
	def user_params
		params.require(:user).permit(:email)
	end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
	def to_weekday(day)
		case day
		when 1
			"Senin"
		when 2
			"Selasa"
		when 3
			"Rabu"
		when 4
			"Kamis"
		when 5
			"Jumat"
		when 6
			"Sabtu"
		when 7
			"Minggu"
		end
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active_page(path, request)
		if request.get?
			"active" if current_page?(path)
		else
			path == "/users/sign_in" ? "active" : ""
		end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def full_name(user_id)
		u = User.find(user_id)
		"#{u.first_name}  #{u.last_name}"
	end

	def gender(user_id)
		u = User.find(user_id)
		u.gender == 0 ? "Laki-laki" : "Perempuan"
	end
end

app/views/admin/admin/index.html.erb
Index page
<%= @user %>

app/views/admin/menus/edit.html.erb
<h1>Edit Menu #<%= @menu.id %></h1>
<%= form_for @menu, :url => admin_menu_path(@menu), :html => {:class => 'form-horizontal register-form'} do |f| %>
	<div class=" form-group control-group">
    <%= f.label :name, :class => 'control-label col-sm-3' %>
    <div class="controls col-sm-8">
      <%= f.text_field :name, autofocus: true, :id => 'input-name', :class => 'form-control' %>
    </div>
  </div>
  <div class=" form-group control-group">
    <%= f.label :price, :class => 'control-label col-sm-3' %>
    <div class="controls col-sm-8">
    	<div class="input-group">
    		<span class="input-group-addon">Rp.</span>
        <%= f.number_field :price, :value => @menu.price/1000, autofocus: true, :id => 'input-price', :class => 'form-control' %>
        <span class="input-group-addon"><small>x1000</small></span>
    	</div>
    </div>
  </div>
  <div class=" form-group control-group">
    <%= f.label :discount, :class => 'control-label col-sm-3' %>
    <div class="controls col-sm-3">
      <%= f.number_field :discount, autofocus: true, :id => 'input-discount', :class => 'form-control' %>
    </div>
  </div>
  <div class=" form-group control-group">
    <%= f.label :rating, :class => 'control-label col-sm-3' %>
    <div class="controls col-sm-3">
      <%= f.number_field :rating, autofocus: true, :id => 'input-discount', :class => 'form-control' %>
    </div>
  </div>
  <div class=" form-group control-group">
    <%= f.label :day, :class => 'control-label col-sm-3' %>
    <div class="controls col-sm-8">
    	<%= f.select(:day, [["Senin", "1"], ["Selasa", "2"], ["Rabu", "3"], ["Kamis", "4"], ["Jumat", "5"], ["Sabtu", "6"], ["Minggu", "7"]], autofocus: true, :id => 'input-name', :class => 'form-control') %>
    </div>
  </div>
  <div class=" form-group control-group">
    <%= f.label :image, :class => 'control-label col-sm-3' %>
    <div class="controls col-sm-8">
      <div class="row">
      	<div class="col-sm-4">
      		<%= image_tag @menu.image.url.to_s, :class => "admin-edit-image" %>
      	</div>
      	<div class="col-sm-3">
      		<%= f.file_field :image, autofocus: true, :id => 'input-image' %>
      	</div>
      </div>
    </div>
  </div>
  <div>
    <%= f.submit "Submit", :class => 'btn btn-primary' %>
    <%= link_to "Cancel", admin_menus_path, :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/admin/menus/index.html.erb
<%= link_to "Add Menu", new_admin_menu_path, :class => "btn btn-primary" %>
<table class="table table-bordered table-striped" style="margin-top:10px;">
	<thead>
		<tr>
			<% @column_names.each do |column| %>
				<th><%= column.capitalize %></th>
			<% end %>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @menus.each do |menu| %>
			<tr>
				<!--<td><%#= menu.id %></td>-->
				<td><%= menu.name %></td>
				<td>Rp. <%= number_with_delimiter(menu.price.to_i, :delimiter => '.') %>,-</td>
				<td><%= image_tag menu.image.url.to_s, :style => "width:20%;height:20%;" %></td>
				<td><%= to_weekday(menu.day) %></td>
				<td><%= menu.discount %></td>
				<td><%= menu.rating %></td>
				<td>
					<%= link_to admin_menu_path(menu), :title => "View", :class => "btn btn-primary" do %>
						<span class="glyphicon glyphicon-eye-open"></span>
					<% end %>
					<%= link_to edit_admin_menu_path(menu), :title => "Edit", :class => "btn btn-info" do %>
						<span class="glyphicon glyphicon-edit"></span>
					<% end %>
					<%= link_to admin_menu_path(menu), :method => :delete, :"data-confirm" => "Are you sure?", :title => "Delete", :class => "btn btn-danger" do %>
						<span class="glyphicon glyphicon-trash"></span>
					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/menus/new.html.erb
<h1>Add New Menu</h1>
<%= form_for @menu, :url => admin_menus_path, :html => {:class => 'form-horizontal register-form'} do |f| %>
  <div class=" form-group control-group">
    <%= f.label :name, :class => 'control-label col-sm-3' %>
    <div class="controls col-sm-8">
      <%= f.text_field :name, autofocus: true, :id => 'input-name', :class => 'form-control' %>
    </div>
  </div>
  <div class=" form-group control-group">
    <%= f.label :price, :class => 'control-label col-sm-3' %>
    <div class="controls col-sm-8">
      <div class="input-group">
        <span class="input-group-addon">Rp.</span>
        <%= f.number_field :price, autofocus: true, :id => 'input-price', :class => 'form-control' %>
        <span class="input-group-addon"><small>x1000</small></span>
      </div>
    </div>
  </div>
  <div class=" form-group control-group">
    <%= f.label :day, :class => 'control-label col-sm-3' %>
    <div class="controls col-sm-8">
      <%= f.select(:day, [["Senin", "1"], ["Selasa", "2"], ["Rabu", "3"], ["Kamis", "4"], ["Jumat", "5"], ["Sabtu", "6"], ["Minggu", "7"]], autofocus: true, :id => 'input-name', :class => 'form-control') %>
    </div>
  </div>
  <div class=" form-group control-group">
    <%= f.label :image, :class => 'control-label col-sm-3' %>
    <div class="controls col-sm-8">
      <%= f.file_field :image, autofocus: true, :id => 'input-image' %>
    </div>
  </div>
  <div>
    <%= f.submit "Submit", :class => 'btn btn-primary' %>
    <%= link_to "Cancel", admin_menus_path, :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/admin/menus/show.html.erb
<div class="row">
	<div class="col-md-4"><%= image_tag @menu.image.url.to_s, :class => "admin-menu-image" %></div>
	<div class="col-md-8 attributes">
		<% @menu.attributes.keys.each do |attribute| %>
			<div class="row">
				<div class="col-md-2"><%= attribute %></div>
				<div class="col-md-1">:</div>
				<div class="col-md-7"><%= @menu.attributes[attribute] %></div>
			</div>
		<% end %>
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<%= link_to "Back", admin_menus_path, :class => "btn btn-default" %>
	</div>
</div>

app/views/admin/users/index.html.erb
<style type="text/css">
	td,th {
		padding: 0px 10px;
	}
</style>
<div class="body">
	<div class="container-fluid">
		<span>User count: <%= @users.size %></span>
		<table class="table table-bordered table-striped">
			<tr>
				<th>No</th>
				<th>Email</th>
				<th>Nama</th>
				<th>No Telepon</th>
				<th>Alamat</th>
				<th>Jenis Kelamin</th>
				<th>Tanggal Lahir</th>
			</tr>
			<% @users.each_with_index do |user, index| %>
			<tr>
				<td><%= index+1 %></td>
				<td><%= user.email %></td>
				<td><%= user.first_name + " " + user.last_name %></td>
				<td><%= user.phone_number %></td>
				<td><%= user.address %></td>
				<td><%= user.gender == 0 ? 'Laki-laki' : 'Perempuan' %></td>
				<td><%= user.birthday.nil? ? '-' : user.birthday %></td>
			</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/home/index.html.erb
<div class="body">
  <div class="container-fluid body-container" >
    <div class="carousel-container">
        <div id="carousel-example-generic" class="carousel slide mycarousel" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
          </ol>
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <%= image_tag 'carousel-food1.jpg' %>
              <div class="carousel-caption">
                <div class="carousel-caption-title">It's simple.</div>
                <div class="carousel-caption-content">Great ingredients make great food</div>
              </div>
            </div>
            <div class="item">
              <%= image_tag 'carousel-food2.jpg' %>
              <div class="carousel-caption">
                <div class="carousel-caption-title">Live. Love. Eat.</div>
                <div class="carousel-caption-content">One cannot think, love, sleep well if one has not dined well.</div>
              </div>
            </div>
            <div class="item">
              <%= image_tag 'carousel-food3.jpg' %>
              <div class="carousel-caption">
                <div class="carousel-caption-title">Good food is good mood.</div>
                <div class="carousel-caption-content">Cooking with love provides food for the soul.</div>
              </div>
            </div>
          </div>
          <!-- Controls -->
          <!--<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
          </a>-->
        </div>
    </div>
    <div class="fav-item-container">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <div class="line-through text-center">
              <p><span class="fav-item-container-title">Menu Favorit</span></p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="fav-item">
              <a href="#">
                <img src="images/fav-item1.jpg"/>
                <div class="fav-item-text">
                  <span class="fav-item-title">Chicken Hamburger</span>
                  <span class="fav-item-price">Rp. 100.000,-</span>
                </div>
              </a>
              <div class="fav-item-controls">
                <a href="#">
                  <div class="fav-controls-order">
                    <span class="glyphicon glyphicon-shopping-cart glyphicon-order" aria-hidden="true"></span>
                    <span class="fav-item-order">Order</span>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="fav-item">
              <a href="#">
                <img src="images/fav-item2.jpg"/>
                <div class="fav-item-text">
                  <span class="fav-item-title">Fried Shrimp</span>
                  <span class="fav-item-price">Rp. 82.500,-</span>
                </div>
              </a>
              <div class="fav-item-controls">
                <a href="#">
                  <div class="fav-controls-order">
                    <span class="glyphicon glyphicon-shopping-cart glyphicon-order" aria-hidden="true"></span>
                    <span class="fav-item-order">Order</span>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="fav-item">
              <a href="#">
                <img src="images/fav-item3.jpg"/>
                <div class="fav-item-text">
                  <span class="fav-item-title">Pancake with Maple Syrup</span>
                  <span class="fav-item-price">Rp. 100.000,-</span>
                </div>
              </a>
              <div class="fav-item-controls">
                <a href="#">
                  <div class="fav-controls-order">
                    <span class="glyphicon glyphicon-shopping-cart glyphicon-order" aria-hidden="true"></span>
                    <span class="fav-item-order">Order</span>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="benefits-container">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-4">
            <div class="benefits-item">
              <img src="images/benefits.png"/>
              <div class="benefits-text">
                <span class="benefits-title">Benefits 1</span>
                <span class="benefits-content">
                  Lorem ipsum dolor sit amet, 
                  consectetur adipiscing elit, 
                  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </span>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="benefits-item">
              <img src="images/benefits.png"/>
              <div class="benefits-text">
                <span class="benefits-title">Benefits 2</span>
                <span class="benefits-content">
                  Lorem ipsum dolor sit amet, 
                  consectetur adipiscing elit, 
                  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </span>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="benefits-item">
              <img src="images/benefits.png"/>
              <div class="benefits-text">
                <span class="benefits-title">Benefits 3</span>
                <span class="benefits-content">
                  Lorem ipsum dolor sit amet, 
                  consectetur adipiscing elit, 
                  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </span>
              </div>
          </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="benefits-item">
              <img src="images/benefits.png"/>
              <div class="benefits-text">
                <span class="benefits-title">Benefits 4</span>
                <span class="benefits-content">
                  Lorem ipsum dolor sit amet, 
                  consectetur adipiscing elit, 
                  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </span>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="benefits-item">
              <img src="images/benefits.png"/>
              <div class="benefits-text">
                <span class="benefits-title">Benefits 5</span>
                <span class="benefits-content">
                  Lorem ipsum dolor sit amet, 
                  consectetur adipiscing elit, 
                  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </span>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="benefits-item">
              <img src="images/benefits.png"/>
              <div class="benefits-text">
                <span class="benefits-title">Benefits 6</span>
                <span class="benefits-content">
                  Lorem ipsum dolor sit amet, 
                  consectetur adipiscing elit, 
                  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_admin_header.html.erb
<div class="admin-header navbar navbar-default">
	<ul class="nav navbar-nav">
		<li><%= link_to "User", admin_users_path %></li>
		<li><%= link_to "Menu", admin_menus_path %></li>
	</ul>
	<ul class="nav navbar-nav pull-right">
		<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
	</ul>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="container-fluid header-container">
    <div class="row">
      <div class="col-md-3 logo-area">
        <%= link_to image_tag('logo-text.png', :class => 'logo-text'), root_path %>
      </div>
      <div class="col-md-6 text-center nav-area">
        <div class="navigation-bar">
          <div class="container">
            <div class="row pull-center row-nav-item">
              <%= link_to root_path do %>
              	<div class="col-md-1 nav-item <%= active_page(root_path, request) %>">Home</div>
              <% end %>
              <%= link_to menus_path do %>
              	<div class="col-md-1 nav-item <%= active_page(menus_path, request) %>">Menu</div>
              <% end %>
              <%= link_to root_path do %>
              	<div class="col-md-1 nav-item <%#= active_page(about_path) %>">About</div>
              <% end %>
              <%= link_to root_path do %>
              	<div class="col-md-1 nav-item <%#= active_page(contact_path) %>">Contact</div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="container">
          <div class="row login-area">
        		<% if user_signed_in? %>
              <%= link_to user_path(@user) do %>
                <div class="col-md-3 login-profile">
                  <div class="dropdown">
                    <a href="#" class="dropdown-toggle dropdown-link" data-toggle="dropdown" rol="button" aria-haspopup="true" aria-expanded="false">
                      Selamat datang, <%= @user.first_name %> <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu profile-login-dropdown-menu">
                      <li>
                        <%= link_to user_path(@user) do %>
                          <i class="glyphicon glyphicon-user"></i> Profil
                        <% end %>
                      </li>
                      <li>
                        <%= link_to edit_user_path(@user) do %>
                          <i class="glyphicon glyphicon-edit"></i> Pengaturan
                        <% end %>
                      </li>
                      <li>
                        <%= link_to '#' do %>
                          <i class="glyphicon glyphicon-shopping-cart"></i> Pembelian
                        <% end %>
                      </li>
                      <li role="separator" class="divider"></li>
                      <% if !@user.admin.zero? ? true : false %>
                      <li>
                        <%= link_to admin_root_path do %>
                          <i class="glyphicon glyphicon-wrench"></i> Admin Panel
                        <% end %>
                      </li>
                      <li role="separator" class="divider"></li>
                      <% end %>
                      <li>
                        <%= link_to destroy_user_session_path, :method => :delete do %>
                          <i class="glyphicon glyphicon-off"></i> Keluar
                        <% end %>
                      </li>
                    </ul>
                  </div>
                </div>
              <% end %>
            <% else %>
              <%= link_to new_user_registration_path do %>
                <div class="col-md-1 login-item <%= active_page(new_user_registration_path, request) %>">Daftar</div>
              <% end %>
              <% if active_page(new_user_session_path, request) == "active" || active_page(user_session_path, request) == "active" %>
                <%= link_to "#" do %>
                  <div class="col-md-1 login-item active">Masuk</div>
                <% end %>
              <% else %>
                <div class="col-md-1 login-item login-dropdown">
                  <div class="dropdown <%= active_page(new_user_session_path, request) %>">
                    <a href="#" class="dropdown-toggle dropdown-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                      Masuk <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu signin-form">
                      <%= form_for(@user, url: new_user_session_path(@user)) do |f| %>
                        <div class="form-group">
                          <%= f.email_field :email, :class => "form-control", :id => "input-email", :placeholder => "Email" %>
                        </div>
                        <div class="form-group">
                          <%= f.password_field :password, :class => "form-control", :id => "input-password", :placeholder => "Password" %>
                        </div>
                        <div class="form-group">
                          <%= f.submit "Masuk", :class => "btn btn-primary btn-accounts" %>
                        </div>
                        <div class="form-group">
                          <%= f.check_box :remember_me %>
                          <%= f.label :remember_me, :class => 'control-label' %>
                        </div>
                      <% end %>
                    </ul>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bikinkenyang - Admin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="main-container">
		<%= render 'layouts/admin_header' %>
		<div class="body">
			<div class="container-fluid">
				<% flash.each do |key, value| %>
					<% if key != "notice" %>
						<div class="alert alert-<%= key %>"><%= value %></div>
					<% end %>
				<% end %>
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/users/show.html.erb
<div class="body">
	<div class="container profile-container">
		<div class="row profile">
			<div class="col-md-3">
				<%= image_tag 'pp.png', :class => "profile-user-pic" %>
			</div>
			<div class="col-md-9">
				<div class="profile-content">
					<div class="profile-info">
						<div class="row">
							<div class="col-md-10">
								<span class="profile-user-name"><%= full_name(@user) %></span>
							</div>
							<div class="col-md-2 edit-profile">
								<%= link_to edit_user_path(@user) do %>
									<span class="btn btn-primary"><i class="glyphicon glyphicon-edit"></i> Ubah Profile</span>
								<% end %>
							</div>
						</div>
						<div class="row">
							<div class="col-md-7 user-info"><i class="glyphicon glyphicon-envelope"></i> <%= @user.email %></div>
						</div>
						<div class="row">
							<div class="col-md-7 user-info"><i class="glyphicon glyphicon-earphone"></i> <%= @user.phone_number %></div>
						</div>
						<div class="row">
							<div class="col-md-7 user-info"><i class="glyphicon glyphicon-home"></i> <%= @user.address %></div>
						</div>
						<div class="row">
							<div class="col-md-7 user-info"><i class="glyphicon glyphicon-home"></i> <%= gender(@user) %></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row profile">
			<div class="col-md-3">
				<ul class="profile-actions-list">
					<li class="profile-actions-list-item-title">Profil Saya</li>
					<li class="profile-actions-list-item">
						<%= link_to '#' do %>
							<i class="glyphicon glyphicon-shopping-cart"></i> Pembelian
						<% end %>
					</li>
					<li class="profile-actions-list-item">
						<%= link_to '#' do %>
							<i class="glyphicon glyphicon-gift"></i> Lihat Poin
						<% end %>
					</li>
					<li class="profile-actions-list-item-title">Lainnya</li>
					<li class="profile-actions-list-item">
						<%= link_to '#' do %>
							<i class="glyphicon glyphicon-envelope"></i> Pesan
						<% end %>
					</li>
					<li class="profile-actions-list-item">
						<%= link_to '#' do %>
							<i class="glyphicon glyphicon-pencil"></i> Review
						<% end %>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>